---
- name: Deployment Cluster Setup
  hosts: localhost
  become: yes
  gather_facts: false
  pre_tasks:
    - pause:
        prompt: "What is the name of your application?"
      register: application
      when: application_name is not defined

    - pause:
        prompt: "Enter Jenkins URL, to setup configuration into Jenkins"
      register: jenkins_address
      when: devops_cluster_dns is not defined and jenkins_url is not defined

    - pause:
        prompt: "Enter Jenkins username, to setup configuration into Jenkins?"
      register: jenkins_uname
      when: jenkins_username is not defined

    - pause:
        prompt: "Enter Jenkins password, to setup configuration into Jenkins"
      register: jenkins_pass
      when: jenkins_password is not defined


  vars:

  tasks:
    - name: Make application name persistant
      set_fact:
        application_name: "{{ hostvars['localhost']['application']['user_input'] }}"
      when: application_name is not defined

    - name: Including Azure credentials configuration values from variable file.
      include_vars:
          file: ../../configurations/common-configurations.yml
          name: common

    - name: Make jenkins_url persistant
      set_fact:
          jenkins_url: "{{ hostvars['localhost']['jenkins_address']['user_input'] }}"
      when: devops_cluster_dns is not defined and jenkins_url is not defined

    - name: Make jenkins_username persistant
      set_fact:
          jenkins_username: "{{ hostvars['localhost']['jenkins_uname']['user_input'] }}"
      when: jenkins_username is not defined

    - name: Make jenkins_password persistant
      set_fact:
          jenkins_password: "{{ hostvars['localhost']['jenkins_pass']['user_input'] }}"
      when: jenkins_password is not defined

    - include_tasks: "./tasks/configure-cluster.yml"
      loop: "{{ common.environments }}"
      loop_control:
        loop_var: env_name

    - include_tasks: "./tasks/create-public-address-and-dns.yml"
      loop: "{{ common.environments }}"
      loop_control:
        loop_var: env_name
